-- ============================================================================
-- CLINICAL REFERENCE SEED DATA -- drugs & drug_interactions
--
-- SCOPE LIMITATION: this is a small, illustrative scaffold dataset for
-- development/testing of the Smart Prescription Engine's safety checker
-- (backend/app/services/prescription_safety.py). It is NOT a clinically
-- complete or validated drug/interaction database, and must never be
-- presented or relied upon as one. A real deployment must integrate a
-- licensed drug/interaction reference source -- e.g. RxNorm, First
-- Databank (FDB), DrugBank, or an equivalent -- in place of (or feeding
-- into) the `drugs`/`drug_interactions` tables this file seeds.
--
-- NOT auto-run: unlike database/schema.sql, this file is NOT picked up by
-- the docker-entrypoint-initdb.d mechanism (that only runs scripts present
-- at container FIRST INIT, and only for schema/bootstrap files placed
-- there deliberately). This is reference/lookup data, not schema, and is
-- meant to be re-run independently of container lifecycle (e.g. to reset
-- or refresh reference data without recreating the database). Apply it
-- manually, after schema.sql, e.g.:
--
--   psql "$DATABASE_URL" -f database/schema.sql
--   psql "$DATABASE_URL" -f database/seed_clinical_reference_data.sql
--
-- Idempotency: this file does NOT guard against re-running (no
-- ON CONFLICT / DELETE-first). Running it twice against the same database
-- will insert duplicate drug/interaction rows (drugs.id is a fresh
-- gen_random_uuid() per run, so there's no natural key to upsert against).
-- For a fresh test/dev database this is fine -- run once after schema.sql.
-- If you need idempotent re-seeding, TRUNCATE drug_interactions, drugs
-- first (in that order, drug_interactions references drugs).
--
-- Patient allergies are NOT seeded here: allergies are patient-specific
-- clinical data recorded via the Phase-2 API
-- (POST /api/v1/patients/{patient_id}/allergies), not reference data. See
-- the "ALLERGY-CLASS EXAMPLES" comment block at the bottom of this file for
-- illustrative (not executable) examples of how allergy substances are
-- expected to relate to the seeded drugs below, for manual testing.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- DRUGS (~14 common drugs spanning a few interaction-relevant classes)
-- ----------------------------------------------------------------------------
INSERT INTO drugs (id, name, generic_name, interaction_class) VALUES
    (gen_random_uuid(), 'Coumadin',    'Warfarin',      'anticoagulant'),
    (gen_random_uuid(), 'Bayer Aspirin','Aspirin',       'nsaid'),
    (gen_random_uuid(), 'Advil',       'Ibuprofen',     'nsaid'),
    (gen_random_uuid(), 'Aleve',       'Naproxen',      'nsaid'),
    (gen_random_uuid(), 'Amoxil',      'Amoxicillin',   'beta-lactam'),
    (gen_random_uuid(), 'Augmentin',   'Amoxicillin/Clavulanate', 'beta-lactam'),
    (gen_random_uuid(), 'Zithromax',   'Azithromycin',  'macrolide'),
    (gen_random_uuid(), 'Lanoxin',     'Digoxin',       'cardiac-glycoside'),
    (gen_random_uuid(), 'Lasix',       'Furosemide',    'loop-diuretic'),
    (gen_random_uuid(), 'Prinivil',    'Lisinopril',    'ace-inhibitor'),
    (gen_random_uuid(), 'Glucophage',  'Metformin',     'biguanide'),
    (gen_random_uuid(), 'Zocor',       'Simvastatin',   'statin'),
    (gen_random_uuid(), 'Biaxin',      'Clarithromycin','macrolide'),
    (gen_random_uuid(), 'Tylenol',     'Acetaminophen', 'analgesic')
ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- DRUG INTERACTIONS -- a handful of well-known, textbook pairs.
-- Severity vocabulary matches prescription_safety.py's classification
-- table: contraindicated | major | moderate | minor.
--
-- NOTE: drug_interactions has no natural key beyond the (drug_a_id,
-- drug_b_id) pair, and the drug ids above are freshly generated by this
-- same script run -- so the interactions below are wired up via name
-- lookups in the same statement (subqueries), not hardcoded UUIDs, which
-- would be meaningless across runs.
-- ----------------------------------------------------------------------------
INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT w.id, a.id, 'major', 'Increased bleeding risk: NSAID displaces warfarin protein binding and impairs platelet function.'
FROM drugs w, drugs a
WHERE w.generic_name = 'Warfarin' AND a.generic_name = 'Aspirin'
ON CONFLICT DO NOTHING;

INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT w.id, i.id, 'major', 'Increased bleeding risk: NSAID displaces warfarin protein binding and impairs platelet function.'
FROM drugs w, drugs i
WHERE w.generic_name = 'Warfarin' AND i.generic_name = 'Ibuprofen'
ON CONFLICT DO NOTHING;

INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT w.id, n.id, 'major', 'Increased bleeding risk: NSAID displaces warfarin protein binding and impairs platelet function.'
FROM drugs w, drugs n
WHERE w.generic_name = 'Warfarin' AND n.generic_name = 'Naproxen'
ON CONFLICT DO NOTHING;

INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT d.id, c.id, 'contraindicated', 'Clarithromycin markedly raises digoxin serum levels (P-glycoprotein inhibition) -- risk of digoxin toxicity.'
FROM drugs d, drugs c
WHERE d.generic_name = 'Digoxin' AND c.generic_name = 'Clarithromycin'
ON CONFLICT DO NOTHING;

INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT s.id, c.id, 'major', 'Clarithromycin (CYP3A4 inhibitor) raises simvastatin levels -- increased risk of myopathy/rhabdomyolysis.'
FROM drugs s, drugs c
WHERE s.generic_name = 'Simvastatin' AND c.generic_name = 'Clarithromycin'
ON CONFLICT DO NOTHING;

INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT f.id, l.id, 'moderate', 'ACE inhibitor + loop diuretic: additive hypotensive effect and risk of renal impairment; monitor renal function and blood pressure.'
FROM drugs f, drugs l
WHERE f.generic_name = 'Furosemide' AND l.generic_name = 'Lisinopril'
ON CONFLICT DO NOTHING;

INSERT INTO drug_interactions (drug_a_id, drug_b_id, severity, description)
SELECT au.id, az.id, 'minor', 'Both may prolong QT interval; additive effect is usually clinically minor but worth noting in patients with existing cardiac risk factors.'
FROM drugs au, drugs az
WHERE au.name = 'Augmentin' AND az.generic_name = 'Azithromycin'
ON CONFLICT DO NOTHING;

-- ============================================================================
-- ALLERGY-CLASS EXAMPLES (illustrative only -- NOT executable inserts;
-- patient_allergies is patient-specific and populated via the Phase-2 API,
-- never seeded as reference data)
--
-- These show how prescription_safety.check_allergy_conflicts's exact,
-- case-insensitive match against drug.name / drug.generic_name /
-- drug.interaction_class is expected to behave against the drugs seeded
-- above, and where its documented false-negative gap shows up:
--
--   1. patient_allergies.substance = 'Amoxicillin'
--      -> matches Amoxil (generic_name = 'Amoxicillin') exactly. Caught.
--
--   2. patient_allergies.substance = 'Penicillin'
--      -> does NOT match Amoxil or Augmentin: neither drug's name,
--         generic_name, or interaction_class ('beta-lactam') is literally
--         the string 'Penicillin'. This is the documented gap: a clinician
--         who records a class-level allergy using a different word than
--         what's in interaction_class will not be caught by this checker.
--         See prescription_safety.py's module docstring.
--
--   3. patient_allergies.substance = 'nsaid'
--      -> matches Bayer Aspirin, Advil, and Aleve (all have
--         interaction_class = 'nsaid'), case-insensitively. This is the
--         one path where a class-level allergy IS caught -- because this
--         seed data's interaction_class happens to equal the substance
--         string the clinician would plausibly type.
-- ============================================================================
